CREATE TABLE patterns (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER DEFAULT 1 NOT NULL,
    name TEXT NOT NULL,
    kick_steps int[16] DEFAULT '{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}' NOT NULL,
    snare_steps int[16] DEFAULT '{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}' NOT NULL,
    hh1_steps int[16] DEFAULT '{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}' NOT NULL,
    hh2_steps int[16] DEFAULT '{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}' NOT NULL,
    clap_steps int[16] DEFAULT '{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}' NOT NULL,
    perc_steps int[16] DEFAULT '{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}' NOT NULL
);